services:
  db_test:
    container_name: db_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: focus
    ports:
      - 4050:5432